<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('categories')->insertOrIgnore([
            // Régions (Site / region)
            [
                'id' => 1,
                'name' => 'Basse Guinée',
                'language_id' => 1,
                'description' => 'Culture et patrimoine de la Basse Guinée.',
                'status' => 1,
                'slug' => 'basse-guinee',
                'video' => null,
                'position' => 0,
                'model' => 'Site',
                'type' => 'region',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Base Guinée',
                'language_id' => 1,
                'description' => 'Culture et patrimoine de la Basse Guinée.',
                'status' => 1,
                'slug' => 'basse-guinee',
                'video' => null,
                'position' => 0,
                'model' => 'Site',
                'type' => 'region',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Guinée Forestière',
                'language_id' => 1,
                'description' => 'L\'ensemble des sites touristiques de la Guinée Forestière.',
                'status' => 1,
                'slug' => 'guinee-forestiere',
                'video' => null,
                'position' => 0,
                'model' => 'Site',
                'type' => 'region',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Haute Guinée',
                'language_id' => 1,
                'description' => 'L\'ensemble des sites touristiques de la Haute Guinée.',
                'status' => 1,
                'slug' => 'haute-guinee',
                'video' => null,
                'position' => 0,
                'model' => 'Faq',
                'type' => 'region',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Moyenne Guinée',
                'language_id' => 1,
                'description' => 'L\'ensemble des sites touristiques de la Moyenne Guinée.',
                'status' => 1,
                'slug' => 'moyenne-guinee',
                'video' => null,
                'position' => 0,
                'model' => 'Faq',
                'type' => 'region',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catégories générales
            [
                'id' => 3,
                'name' => 'Tourisme',
                'language_id' => 1,
                'description' => 'Les attractions touristiques.',
                'status' => 1,
                'slug' => 'tourisme',
                'video' => null,
                'position' => 0,
                'model' => 'Product',
                'type' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Voyage',
                'language_id' => 1,
                'description' => 'Destinations et conseils de voyage.',
                'status' => 1,
                'slug' => 'voyage',
                'video' => null,
                'position' => 0,
                'model' => 'Product',
                'type' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catégories Hôtel
            [
                'id' => 2,
                'name' => 'Centre-ville',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-centre-ville',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Luxe',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-luxe',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Économique',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-economique',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Business',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-business',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Boutique',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-boutique',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Resort',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-resort',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Eco-responsable',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-eco-responsable',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Aéroport',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-aeroport',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Montagne',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-montagne',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Bord de mer',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'hotel-bord-de-mer',
                'video' => null,
                'position' => 0,
                'model' => 'Hotel',
                'type' => 'hotel_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catégories Chambre
            [
                'id' => 16,
                'name' => 'Suite',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-suite',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Deluxe',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-deluxe',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Supérieure',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-superieure',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Standard',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-standard',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Familiale',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-familiale',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Single',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-single',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Double',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-double',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Twin',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-twin',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Studio',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-studio',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Suite Présidentielle',
                'language_id' => 1,
                'description' => null,
                'status' => 1,
                'slug' => 'room-suite-presidentielle',
                'video' => null,
                'position' => 0,
                'model' => 'Room',
                'type' => 'room_type',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
